// <auto-generated />
using System;
using ConnectHubAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectHubAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250811144627_migra")]
    partial class migra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConnectHubAPI.Model.MenuGeral_Modulo", b =>
                {
                    b.Property<int>("MenuGeral_ModuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MenuGeral_ModuloId"));

                    b.Property<string>("mgm_descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MenuGeral_ModuloId");

                    b.ToTable("MenuGeral_Modulo");
                });

            modelBuilder.Entity("ConnectHubAPI.Model.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<bool>("Confirmacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("whatsAppNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ConnectHubAPI.Model.Respostas_Padrao", b =>
                {
                    b.Property<int>("rep_resposta_padraoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("rep_resposta_padraoId"));

                    b.Property<int>("MenuGeral_ModuloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("rep_data_alteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("rep_pergunta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rep_resposta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("rep_resposta_padraoId");

                    b.HasIndex("MenuGeral_ModuloId");

                    b.ToTable("respostas_padroes");
                });

            modelBuilder.Entity("ConnectHubAPI.Model.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ConnectHubAPI.Model.Respostas_Padrao", b =>
                {
                    b.HasOne("ConnectHubAPI.Model.MenuGeral_Modulo", "MenuGeral_Modulo")
                        .WithMany()
                        .HasForeignKey("MenuGeral_ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuGeral_Modulo");
                });
#pragma warning restore 612, 618
        }
    }
}
